### ISSUE TITLE
Migration from JCenter to MavenCentral

### ISSUE THREAD

**Issue by esantamaria** [datatheorem/TrustKit-Android#84] opened 2021-03-29 21:16 UTC
**Is your feature request related to a problem? Please describe.**
With the announcement of Bintray/JCenter to be shutdown, the bast majority of libraries are already (or migrating) to mavenCentral, however, trustkit is still only available on JCenter.

**Describe the solution you'd like**
Migrate the trustkit library to MavenCenter

**Additional context**
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by nabla-c0d3** [comment] 2021-03-30 15:54
Closing this as a duplicate of https://github.com/datatheorem/TrustKit-Android/issues/81. We are working on the migration right now.

**Closed by nabla-c0d3** 2021-03-30 15:54 UTC
