### ISSUE TITLE
api can be intercepted by Burp after implemented it if android API level < 24 

### ISSUE THREAD

**Issue by wxhawk** [datatheorem/TrustKit-Android#38] opened 2018-08-23 04:09 UTC
after implemented it in android, the api still can be intercepted by Burp, you can see the request/response and modify them, if api level <24, it is not supposed to happen.

**Comment by nabla-c0d3** [comment] 2018-08-24 03:40
Have you used this in your config: `<trustkit-config enforcePinning="true">` ?

**Comment by wxhawk** [comment] 2018-08-24 09:44
@nabla-c0d3  yes, I did, but that does not help.

**Comment by jobot0** [comment] 2018-09-04 09:06
Hey @wxhawk are you still experiencing this issue ? Because I was not able to reproduce the problem.

**Comment by wxhawk** [comment] 2018-09-04 09:11
@jobot0 good news!!!
How did you reproduce it? did you use Burp as proxy to intercept all the network traffic from mobile app?
Can you share the details what you did in your app so that I can try on my side?

**Comment by jobot0** [comment] 2018-09-12 08:17
@wxhawk sorry for the delay of my answer. I just did the minimal Burp test (meaning just installed Burp on a device (23), trying to intercept the request) and the TrustKit seems to work. I need to setup a Reactive Native environment. I have not done myself the support for React Native but I'll definitely have a look to understand why you still have the issue.

**Comment by ppamorim** [comment] 2018-09-25 12:58
I am having the same issue with a native app.

**Comment by jobot0** [comment] 2018-10-04 08:07
Hey @wxhawk quick update I'm still investigating the issue 😅  Sorry for the delay I had a lot of on my plate recently. 

@ppamorim are you talking about a Reactive Native app or native app written only with the Android framework ?

**Comment by AbhishekCode** [comment] 2018-10-16 14:20
Facing similar issue. my targetSdkVersion is 26 And enforcePinning is true.

**Comment by nabla-c0d3** [comment] 2019-03-17 19:43
TrustKit does not officially support react-native (we've never tested it) so I'll close this issue. If the problem is still happening with a non-react app, please open a new ticket with a copy of your network policy configuration.
Thanks!

**Closed by nabla-c0d3** 2019-03-17 19:43 UTC
Labels: under investigation
